[tools]
starship = "1.19.0"
ghq = "1.6.1"
fzf = "0.53.0"
chezmoi = "2.50.0"
k9s = "latest"
helm = "3.19.5"
helmfile = "1.2.3"
node = "22.4.0"
rust = "1.79.0"
age = "1.1.1"
sops = "3.9.0"
ripgrep = "14.1.0"
cloudflared = "latest"
python = "3.12.4"
fd = "10.1.0"
hugo = "0.134.1"
go = "1.25.3"
redis = "7.4.1"
kubent = "0.7.3"
kubectx = "0.9.5"
pluto = "5.21.1"
zig = "0.13.0"
lima = "1.0.6"
yq = "4.45.1"
stern = "latest"
lazygit = "latest"
uv = "latest"
k6 = "latest"
krew = "0.4.5"
flux2 = "2.6.3"
gh = "latest"
kubens = "0.9.5"
jq = "latest"
java = "21"
"ubi:godotengine/godot" = { version = "4.4.1-stable", matching = "linux.x86_64", exe = "Godot_v4.4.1-stable_linux.x86_64" }
kubectl = "1.32.7"
"aqua:neovim" = "0.12.3"
